services:
  mongodb:
    image: mongo:7
    container_name: polly-voice-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: polly_voice
    volumes:
      - polly_voice_mongodb:/data/db

volumes:
  polly_voice_mongodb:
